name: Runner Build/Push

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 6'

jobs:
  buildx:
    # runs-on: github-arc-runner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        # with:
        #   driver: docker-container

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        # with:
        #   driver: docker-container
      
      - name: Login to DockerHub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
          
      - name: Run Buildx docker
        run: |
          docker buildx build --platform linux/amd64 -t tcousin/esphome-reflash-build:latest -t tcousin/esphome-reflash-build:$GITHUB_SHA --push ./
